### ISSUE TITLE
Support launching arm64 instance types

### ISSUE THREAD

**Issue by aaronwalker** [base2Services/bastion-cli#11]
Got this error when trying to use a c6g.large instance type

```bash
2021/12/15 11:39:20 [ERROR] InvalidParameterValue: The architecture 'arm64' of the specified instance type does not match the architecture 'x86_64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.
	status code: 400, request id: bf9852d1-07dc-4d8f-8ffd-00e6e9ac598b
```

**Comment by Guslington** [comment]
@aaronwalker the bastion cli looks up the latest amazon ami using the amazon ssm parameter, a work around would be to supply the amazon linux arm ssm parameter path along with the arm instance type.

```sh
bastion launch --ami /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2 --instance-type c6g.large
```

to do this based upon instance type we would need to lookup the architecture from the instance type and then select the correct ssm parameter

**Comment by tarunmenon95** [comment]
1) Find all allowed architectures for given instance type
2) Find AMI's that use allowed architecture types
